version: '3'
services:
  rider-server:
    container_name: rider-server
    image: rider-server
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: rider-network
